"""Policy Knowledge Base Retrieval Tools (SDD §3.2, §3.3, UC-1.1).

Provides deterministic, grounded retrieval over `elevate-apac-m3-policydoc.md`
and `knowledge/` markdown files with section-level citations (`Section X.Y`).

Document format (official customer-provided handbook, 1,176 lines)
------------------------------------------------------------------
The handbook does NOT use ATX markdown headings (`# N.M Title`). Instead it
uses bold-text headings::

    **SECTION 5: ETHICS, COMPLIANCE, & CONDUCT perimeters**

    **5.4 Remote Work, Telework, & Data Security**

    * **Home Office Equipment Allowance:** ... $500 USD ...

Some sub-section headings are followed by body text *on the same line*::

    **7.1 General Commitment and Applicability** Altostrat has an unwavering...

The parser below handles both shapes, keeps the parent `SECTION N` title on
every `N.M` chunk, and normalises markdown escaping (`\\-`, `&nbsp;`, trailing
double-spaces) without mangling figures such as `$500 USD` or `'4 - Low'`.

Public API (stable - consumed by `app/agent.py` and `ui/server.py`):
    - search_policy(query, caller_id)
    - list_policy_concepts(caller_id)
    - read_policy_concept(concept_id, caller_id)
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Audit logging hook.
#
# In production this module is imported as `app.tools.policy_tools`, so the
# normal package import works.  When the module is loaded standalone (e.g. via
# importlib for tests, so that a broken sibling in `app/tools/__init__.py`
# cannot break policy retrieval) we fall back to loading `adapter.py` directly
# by path, and finally to a no-op logger.  Behaviour of the public API is
# unchanged either way.
# ---------------------------------------------------------------------------
try:  # pragma: no cover - exercised implicitly by the running agent
    from app.tools.adapter import log_audit_event  # type: ignore
except Exception:  # pragma: no cover - standalone / degraded import path
    try:
        import importlib.util as _importlib_util

        _adapter_path = Path(__file__).resolve().parent / "adapter.py"
        _spec = _importlib_util.spec_from_file_location(
            "_policy_tools_adapter", _adapter_path
        )
        if _spec is None or _spec.loader is None:  # pragma: no cover
            raise ImportError(_adapter_path)
        _adapter = _importlib_util.module_from_spec(_spec)
        _spec.loader.exec_module(_adapter)
        log_audit_event = _adapter.log_audit_event  # type: ignore[assignment]
    except Exception:  # pragma: no cover - last resort

        def log_audit_event(**_kwargs: Any) -> str:  # type: ignore[misc]
            """No-op audit fallback used when the adapter cannot be imported."""
            return "AUD-UNAVAILABLE"


REPO_ROOT = Path(__file__).resolve().parent.parent.parent
POLICY_DOC_PATH = REPO_ROOT / "elevate-apac-m3-policydoc.md"
KNOWLEDGE_DIR = REPO_ROOT / "knowledge"

#: Generated by `scripts/build_knowledge.py`; one file per `N.M` section.
KNOWLEDGE_FILE_TEMPLATE = "section-{number}.md"

# ---------------------------------------------------------------------------
# Text normalisation
# ---------------------------------------------------------------------------

#: Markdown escapes used throughout the handbook (e.g. `'3 \- Moderate'`,
#: `T\&E`, `12\.`, `\>$10,000`).  Unescaping is safe: it never touches digits.
_ESCAPE_RE = re.compile(r"\\([\\`*_{}\[\]()#+\-.!>&$~|<'\"])")
_NBSP_RE = re.compile(r"(&nbsp;|\u00a0)")
_TRAILING_WS_RE = re.compile(r"[ \t]+$", re.MULTILINE)
_MULTI_BLANK_RE = re.compile(r"\n{3,}")


def normalize_policy_text(text: str) -> str:
    """Normalise handbook text for display/citation without altering figures.

    Removes markdown escape backslashes (``'4 \\- Low'`` -> ``'4 - Low'``),
    converts ``&nbsp;`` to a plain space, drops Markdown hard-break trailing
    spaces and collapses runs of blank lines.  Dollar amounts, dates and
    percentages are preserved verbatim.
    """
    if not text:
        return ""
    out = text.replace("\r\n", "\n").replace("\r", "\n")
    out = _NBSP_RE.sub(" ", out)
    out = _ESCAPE_RE.sub(r"\1", out)
    out = _TRAILING_WS_RE.sub("", out)
    out = _MULTI_BLANK_RE.sub("\n\n", out)
    return out.strip()


def _searchable(text: str) -> str:
    """Lowercase, markup-stripped projection of `text` used for scoring."""
    out = normalize_policy_text(text).lower()
    out = out.replace("**", " ").replace("*", " ")
    out = out.replace("→", " -> ")
    out = re.sub(r"[ \t]+", " ", out)
    return out


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


# ---------------------------------------------------------------------------
# Handbook parser
# ---------------------------------------------------------------------------

#: `**SECTION 5: ETHICS, COMPLIANCE, & CONDUCT perimeters**`
_PARENT_RE = re.compile(r"^\*\*SECTION\s+(\d+)\s*:\s*(.+?)\*\*[ \t]*$", re.MULTILINE)

#: `**5.4 Remote Work, Telework, & Data Security**` optionally followed by body
#: text on the same line (`**7.1 General Commitment...** Altostrat has ...`).
_SUB_RE = re.compile(r"^\*\*(\d+\.\d+)\s+(.+?)\*\*[ \t]*(.*)$", re.MULTILINE)


def _clean_title(title: str) -> str:
    return normalize_policy_text(title).replace("**", "").strip().strip(":").strip()


def parse_policy_document(text: str | None = None) -> list[dict[str, Any]]:
    """Parse the handbook into `N.M` section chunks with parent-section context.

    Returns a list of dicts ordered by their position in the document. Each
    dict carries: ``section_id`` (``"Section 5.4"``), ``number`` (``"5.4"``),
    ``title``, ``parent_section_id``, ``parent_number``, ``parent_title``,
    ``content`` (normalised verbatim body, heading line included),
    ``line_start`` / ``line_end`` and ``citation_url``.
    """
    if text is None:
        if not POLICY_DOC_PATH.exists():
            return []
        text = POLICY_DOC_PATH.read_text(encoding="utf-8")
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # Offset -> 1-based line number helper.
    line_starts = [0]
    for m in re.finditer(r"\n", text):
        line_starts.append(m.end())

    def line_of(pos: int) -> int:
        lo, hi = 0, len(line_starts) - 1
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if line_starts[mid] <= pos:
                lo = mid
            else:
                hi = mid - 1
        return lo + 1

    parents = [
        {
            "number": m.group(1),
            "title": _clean_title(m.group(2)),
            "start": m.start(),
            "end": m.end(),
        }
        for m in _PARENT_RE.finditer(text)
    ]
    subs = list(_SUB_RE.finditer(text))

    # Boundaries: a chunk ends at the next sub-section OR the next parent.
    boundaries = sorted(
        [p["start"] for p in parents] + [s.start() for s in subs] + [len(text)]
    )

    def next_boundary(pos: int) -> int:
        for b in boundaries:
            if b > pos:
                return b
        return len(text)

    def parent_for(pos: int) -> dict[str, Any] | None:
        current = None
        for p in parents:
            if p["start"] <= pos:
                current = p
            else:
                break
        return current

    sections: list[dict[str, Any]] = []
    used_ids: set[str] = set()
    parents_with_children: set[str] = set()

    def _add(record: dict[str, Any]) -> None:
        sec_id = record["section_id"]
        if sec_id in used_ids:  # the source doc reuses "SECTION 30" twice
            suffix = 2
            while f"{sec_id} ({suffix})" in used_ids:
                suffix += 1
            record["section_id"] = f"{sec_id} ({suffix})"
        used_ids.add(record["section_id"])
        sections.append(record)

    for match in subs:
        number = match.group(1)
        title = _clean_title(match.group(2))
        inline_body = match.group(3).strip()
        parent = parent_for(match.start())
        if parent is not None:
            parents_with_children.add(parent["number"] + "@" + str(parent["start"]))

        body_start = match.end()
        body_end = next_boundary(match.start())
        body = text[body_start:body_end]
        if inline_body:
            # Heading and body shared a line: keep only the heading in `title`
            # and push the remainder to the front of the body.  `match.end()`
            # already sits past the inline remainder, so just prepend it.
            body = inline_body + "\n\n" + body
        body = normalize_policy_text(body)

        parent_number = parent["number"] if parent else ""
        parent_title = parent["title"] if parent else ""
        heading = f"**{number} {title}**"
        content = f"{heading}\n\n{body}".strip() if body else heading

        line_start = line_of(match.start())
        line_end = max(line_start, line_of(max(body_end - 1, match.start())))
        _add(
            {
                "section_id": f"Section {number}",
                "number": number,
                "title": title,
                "parent_section_id": f"SECTION {parent_number}" if parent_number else "",
                "parent_number": parent_number,
                "parent_title": parent_title,
                "content": content,
                "line_start": line_start,
                "line_end": line_end,
                "citation_url": (
                    f"file://{POLICY_DOC_PATH}#L{line_start}-L{line_end}"
                ),
                "anchor": _slug(f"{number}-{title}"),
            }
        )

    # Parent sections that have no `N.M` children at all (e.g. "SECTION 30:
    # New Employee Onboarding Guidelines") would otherwise be unsearchable.
    for idx, parent in enumerate(parents):
        key = parent["number"] + "@" + str(parent["start"])
        if key in parents_with_children:
            continue
        start = parent["start"]
        end = parents[idx + 1]["start"] if idx + 1 < len(parents) else len(text)
        body = normalize_policy_text(text[parent["end"] : end])
        if not body:
            continue
        heading = f"**SECTION {parent['number']}: {parent['title']}**"
        line_start = line_of(start)
        line_end = max(line_start, line_of(max(end - 1, start)))
        record = {
            "section_id": f"Section {parent['number']}",
            "number": parent["number"],
            "title": parent["title"],
            "parent_section_id": f"SECTION {parent['number']}",
            "parent_number": parent["number"],
            "parent_title": parent["title"],
            "content": f"{heading}\n\n{body}".strip(),
            "line_start": line_start,
            "line_end": line_end,
            "citation_url": f"file://{POLICY_DOC_PATH}#L{line_start}-L{line_end}",
            "anchor": _slug(f"{parent['number']}-{parent['title']}"),
        }
        # keep document order
        insert_at = len(sections)
        for i, existing in enumerate(sections):
            if existing["line_start"] > line_start:
                insert_at = i
                break
        used_ids.add(record["section_id"])
        sections.insert(insert_at, record)

    for sec in sections:
        knowledge_file = KNOWLEDGE_DIR / KNOWLEDGE_FILE_TEMPLATE.format(
            number=sec["number"]
        )
        sec["knowledge_url"] = f"file://{knowledge_file}"
        sec["_haystack_title"] = _searchable(f"{sec['title']} {sec['parent_title']}")
        sec["_haystack_body"] = _searchable(sec["content"])
    return sections


def _load_policy_sections() -> list[dict[str, Any]]:
    """Backwards-compatible alias retained for existing callers/tests."""
    return parse_policy_document()


_CACHED_SECTIONS: list[dict[str, Any]] | None = None
_CACHED_MTIME: float | None = None


def _get_sections() -> list[dict[str, Any]]:
    global _CACHED_SECTIONS, _CACHED_MTIME
    try:
        mtime = POLICY_DOC_PATH.stat().st_mtime
    except OSError:
        mtime = None
    if _CACHED_SECTIONS is None or mtime != _CACHED_MTIME:
        _CACHED_SECTIONS = _load_policy_sections()
        _CACHED_MTIME = mtime
    return _CACHED_SECTIONS


# ---------------------------------------------------------------------------
# Query understanding (JA -> EN synonym expansion)
# ---------------------------------------------------------------------------

#: Japanese (and a few English) trigger substrings mapped to English handbook
#: vocabulary.  The agent answers in Japanese, so Japanese questions must still
#: retrieve the English source text deterministically.
_SYNONYMS: dict[str, list[str]] = {
    # --- Leave / time off -------------------------------------------------
    "有給休暇": ["paid vacation leave", "vacation", "annual leave", "paid time off"],
    "有給": ["paid vacation leave", "vacation", "annual leave", "paid"],
    "年休": ["vacation", "annual leave"],
    "休暇": ["leave", "vacation", "time off"],
    "休み": ["leave", "time off"],
    "何日": ["days", "allowance"],
    "日数": ["days", "allowance", "accrual"],
    "繰越": ["carryover", "carry over", "forfeited"],
    "取得": ["request", "take", "eligibility"],
    "病欠": ["sick leave", "sick", "outpatient", "medical certificate"],
    "病気": ["sick", "illness", "medical"],
    "傷病": ["sick", "hospitalization"],
    "入院": ["hospitalization", "inpatient"],
    "診断書": ["medical certificate", "mc", "medical practitioner"],
    "育児休暇": ["childcare leave", "childcare"],
    "育児": ["childcare", "parental", "baby bonding"],
    "看護": ["carer", "carer's leave"],
    "介護": ["carer", "carer's leave", "compassionate"],
    "産休": ["maternity leave", "maternity"],
    "出産": ["maternity", "childbirth", "parental leave"],
    "忌引": ["bereavement"],
    "慶弔": ["bereavement", "compassionate"],
    "無給": ["unpaid", "unpaid time off", "personal leave"],
    "代休": ["time off in lieu", "toil"],
    "振替休日": ["time off in lieu", "toil", "floating holiday"],
    "祝日": ["public holiday", "floating holiday"],
    "残業": ["overtime", "time off in lieu", "toil"],
    # --- Remote work ------------------------------------------------------
    "在宅勤務": ["remote", "telework", "hybrid", "work from home", "wfh"],
    "在宅": ["remote", "telework", "work from home", "wfh"],
    "リモート": ["remote", "telework", "hybrid"],
    "テレワーク": ["telework", "remote"],
    "ハイブリッド": ["hybrid", "remote"],
    "自宅": ["home", "home office", "remote"],
    "オフィス備品": ["home office equipment", "equipment", "monitors"],
    "備品": ["equipment", "home office equipment", "hardware", "monitors"],
    "機材": ["equipment", "hardware", "monitors"],
    "モニター": ["monitors", "equipment"],
    "手当": ["allowance", "reimbursement"],
    "上限": ["capped", "cap", "limit", "allowance", "up to", "maximum"],
    "限度": ["capped", "cap", "limit", "allowance"],
    "いくら": ["allowance", "usd", "capped", "cost"],
    # --- Expenses ---------------------------------------------------------
    "経費": ["expense", "reimbursement", "expense report", "concur"],
    "精算": ["reimbursement", "expense submission", "concur"],
    "立替": ["reimbursement", "out of pocket"],
    "出張": ["travel", "business travel", "lodging", "booking"],
    "宿泊": ["lodging", "hotel", "accommodation"],
    "食事": ["meal", "meal allowance"],
    "法人カード": ["company card", "corporate card"],
    "領収書": ["receipt", "expense report"],
    # --- Relocation / transfer -------------------------------------------
    "転勤": ["relocation", "transferring", "transfer", "international offices"],
    "異動": ["transfer", "transferring", "relocation"],
    "引越": ["relocation", "moving", "relocation allowance"],
    "引っ越": ["relocation", "moving", "relocation allowance"],
    "海外": ["international", "global", "international offices", "london hq"],
    "赴任": ["relocation", "transferring", "international offices"],
    "費用": ["expenses", "allowance", "cost", "reimbursement"],
    "バッジ": ["badging", "physical building badging", "security access"],
    "入館": ["badging", "building", "security access"],
    # --- ITSM -------------------------------------------------------------
    "チケット": ["ticket", "tickets", "itsm", "service tickets"],
    "案件": ["ticket", "case", "itsm"],
    "優先度": ["priority", "priority definitions", "low", "moderate"],
    "優先順位": ["priority", "priority definitions"],
    "ステータス": ["state", "status", "ticket lifecycle"],
    "状態": ["state", "operational states", "ticket lifecycle"],
    "遷移": ["transition", "ticket lifecycle", "operational states", "sequentially"],
    "変更": ["change", "modify", "transition", "operational states"],
    "直接": ["directly", "bypassing", "intermediate states"],
    "クローズ": ["closed", "resolved"],
    "修理": ["repair", "facilities", "facility issues", "maintenance"],
    "故障": ["broken", "facility issues", "repair"],
    "不具合": ["issue", "facility issues", "defect"],
    "椅子": ["chair", "squeaky office chair", "facility issues"],
    "いす": ["chair", "squeaky office chair"],
    "きしむ": ["squeaky", "squeaky office chair", "cosmetic wear"],
    "軋む": ["squeaky", "squeaky office chair"],
    "設備": ["facilities", "facility issues", "office"],
    # --- Ethics / conduct -------------------------------------------------
    "接待": ["entertainment", "business courtesies", "gifts", "hospitality"],
    "贈": ["gift", "gifts", "business courtesies", "giving"],
    "贈答": ["gift", "gifts", "business courtesies"],
    "ギフト": ["gift", "gifts", "gift card"],
    "商品券": ["gift card", "cash equivalents", "gift cards"],
    "賄賂": ["bribery", "anti-bribery", "kickback"],
    "公務員": ["government official", "government"],
    "禁止": ["prohibited", "prohibitions", "must not", "strictly prohibited"],
    "いけない": ["prohibited", "must not", "cannot"],
    "だめ": ["prohibited", "must not"],
    "利益相反": ["conflicts of interest", "conflict of interest"],
    "ハラスメント": ["harassment", "sexual harassment", "misconduct"],
    "セクハラ": ["sexual harassment", "harassment"],
    "パワハラ": ["bullying", "abusive conduct", "harassment"],
    "いじめ": ["bullying", "abusive conduct"],
    "差別": ["discrimination", "protected statuses"],
    "報告先": ["reporting concerns", "report", "hr", "manager obligations"],
    "報告": ["report", "reporting", "reporting concerns", "disclose"],
    "通報": ["report", "reporting concerns", "raise a concern"],
    "相談": ["report", "reporting concerns", "support"],
    "報復": ["retaliation", "non-retaliation"],
    "恋愛": ["romantic", "personal relationships", "relationships"],
    "交際": ["romantic", "relationships", "dating"],
    "飲酒": ["alcohol", "drinking"],
    "喫煙": ["smoking"],
    "薬物": ["drugs", "controlled substances"],
    "機密": ["confidential", "confidentiality", "proprietary"],
    "情報漏": ["leaks", "confidentiality", "preventing leaks"],
    "副業": ["outside employment", "business ventures"],
    "個人情報": ["employee privacy", "personal data", "privacy"],
    "プライバシー": ["privacy", "employee privacy"],
    "退職": ["exit policy", "termination", "notice of termination", "separation"],
    "解雇": ["termination", "disciplinary"],
    "懲戒": ["disciplinary", "progressive disciplinary process"],
    "評価": ["performance management", "performance"],
    "給与": ["payroll", "salary", "compensation"],
    "賞与": ["bonus", "compensation"],
    "保険": ["health insurance", "insurance", "claims"],
    "安全": ["health and safety", "workplace health", "wsh"],
    "苦情": ["grievance", "dispute resolution", "complaint"],
    "苦情処理": ["grievance", "formal grievance process"],
    "研修": ["training", "mandatory training"],
    "入社": ["onboarding", "new employee", "first week"],
    "フレックス": ["flexible work", "flexible working request"],
    "時短": ["flexible work", "part-time", "flexible working request"],
    "ソーシャルメディア": ["social media", "acceptable use"],
    "sns": ["social media", "acceptable use"],
    # --- English shorthands ----------------------------------------------
    "wfh": ["work from home", "remote", "telework"],
    "pto": ["paid time off", "vacation", "leave"],
    "toil": ["time off in lieu", "toil"],
    "mc": ["medical certificate"],
    "itsm": ["itsm", "ticket", "service tickets"],
}

#: Low-signal English tokens removed from the direct-term list.
_STOPWORDS = {
    "the", "a", "an", "and", "or", "of", "to", "for", "in", "on", "at", "is",
    "are", "was", "were", "be", "been", "can", "could", "do", "does", "did",
    "how", "what", "when", "where", "which", "who", "why", "with", "my", "me",
    "i", "we", "you", "your", "our", "it", "this", "that", "there", "if",
    "about", "from", "by", "as", "any", "all", "not", "but", "have", "has",
    "had", "should", "would", "will", "shall", "may", "much", "many", "get",
    "please", "tell", "want", "need", "know",
}

_ASCII_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9'\-]*|\d+(?:[.,]\d+)*")
_SECTION_REF_RE = re.compile(r"\b(\d+\.\d+)\b")


def _build_query_terms(query: str) -> list[tuple[str, float]]:
    """Expand `query` into weighted lowercase search terms (deterministic)."""
    q = normalize_policy_text(query).lower()
    terms: dict[str, float] = {}

    def add(term: str, weight: float) -> None:
        term = term.strip().lower()
        if not term or term in _STOPWORDS:
            return
        if len(term) < 2 and not term.isdigit():
            return
        terms[term] = max(terms.get(term, 0.0), weight)

    # 1. Direct ASCII tokens straight from the question (highest confidence).
    for tok in _ASCII_TOKEN_RE.findall(q):
        add(tok, 1.0)

    # 2. Synonym expansion driven by substring triggers (handles Japanese,
    #    which has no whitespace tokenisation).
    for trigger, expansions in _SYNONYMS.items():
        if trigger in q:
            for exp in expansions:
                add(exp, 0.85)

    return sorted(terms.items(), key=lambda kv: (-kv[1], kv[0]))


def _count_exact(haystack: str, term: str) -> int:
    return len(re.findall(r"(?<![a-z0-9])" + re.escape(term) + r"(?![a-z0-9])", haystack))


def _score_section(
    section: dict[str, Any], terms: list[tuple[str, float]], raw_query: str
) -> float:
    """Deterministic keyword score: exact term > heading hit > partial body hit."""
    title_hay = section["_haystack_title"]
    body_hay = section["_haystack_body"]
    score = 0.0

    for term, weight in terms:
        matched_title = False
        if _count_exact(title_hay, term):
            score += 8.0 * weight
            matched_title = True
        elif term in title_hay:
            score += 4.0 * weight
            matched_title = True

        exact_body = _count_exact(body_hay, term)
        if exact_body:
            score += min(exact_body, 4) * (3.0 if " " in term else 2.5) * weight
        elif term in body_hay:
            score += min(body_hay.count(term), 4) * 0.75 * weight
        elif not matched_title and " " in term:
            # Multi-word synonym: give partial credit when every word is present.
            words = term.split()
            if all(_count_exact(body_hay, w) for w in words):
                score += 1.5 * weight

    # Whole-question phrase match (English queries).
    q_norm = _searchable(raw_query).strip()
    if len(q_norm) > 8 and q_norm in body_hay:
        score += 12.0

    # Explicit section references ("5.4", "Section 25.3").
    for ref in _SECTION_REF_RE.findall(raw_query):
        if ref == section["number"]:
            score += 30.0
        elif section["number"].startswith(ref.split(".")[0] + "."):
            score += 2.0

    return score


#: Minimum score required before a section is considered a genuine hit.
_SCORE_THRESHOLD = 3.0
_MAX_RESULTS = 5
_MAX_CONTENT_CHARS = 3000


def _section_sort_key(section: dict[str, Any]) -> tuple[int, int]:
    major, _, minor = section["number"].partition(".")
    return (int(major), int(minor) if minor else 0)


def _as_result(section: dict[str, Any], score: float | None = None) -> dict[str, Any]:
    """Project an internal section record onto the stable public result shape."""
    result: dict[str, Any] = {
        "section_id": section["section_id"],
        "title": section["title"],
        "content": section["content"][:_MAX_CONTENT_CHARS],
        "citation_url": section["citation_url"],
        "parent_section": (
            f"{section['parent_section_id']}: {section['parent_title']}"
            if section.get("parent_title")
            else ""
        ),
        "knowledge_url": section.get("knowledge_url", ""),
    }
    if score is not None:
        result = {"score": round(score, 2), **result}
    return result


# ---------------------------------------------------------------------------
# Public tools
# ---------------------------------------------------------------------------


def list_policy_concepts(caller_id: str = "EMP-1001") -> dict[str, Any]:
    """List available HR & IT policy sections and high-level topics in the Policy Knowledge Base.

    Args:
        caller_id: Employee ID of the user requesting the list (default: EMP-1001).

    Returns:
        Dictionary containing a list of policy sections with their section_id and title.
    """
    log_audit_event(
        actor_id=caller_id,
        target_employee_id=caller_id,
        tool_name="list_policy_concepts",
        target_system="PolicyKnowledgeBase",
        action_type="READ",
        decision="ALLOW",
        request_summary={"action": "list_policy_concepts"},
    )
    sections = _get_sections()
    summary = [
        {
            "section_id": s["section_id"],
            "title": s["title"],
            "parent_section": (
                f"{s['parent_section_id']}: {s['parent_title']}"
                if s.get("parent_title")
                else ""
            ),
        }
        for s in sections
    ]
    return {
        "status": "SUCCESS",
        "total_sections": len(summary),
        "sections": summary,
    }


def read_policy_concept(concept_id: str, caller_id: str = "EMP-1001") -> dict[str, Any]:
    """Read the full verbatim text of a specific policy section or concept ID.

    Args:
        concept_id: Section identifier (e.g., "Section 5.4", "25.3", "1.2", "childcare",
                    "host gift") or topic keyword.
        caller_id: Employee ID of the caller (default: EMP-1001).

    Returns:
        Dictionary containing the verbatim policy section text and mandatory citation metadata.
    """
    log_audit_event(
        actor_id=caller_id,
        target_employee_id=caller_id,
        tool_name="read_policy_concept",
        target_system="PolicyKnowledgeBase",
        action_type="READ",
        decision="ALLOW",
        request_summary={"concept_id": concept_id},
    )
    sections = _get_sections()
    raw = (concept_id or "").strip()
    query_norm = re.sub(r"^section\s*", "", raw, flags=re.IGNORECASE).strip().lower()
    query_norm = query_norm.strip(".:# ")

    matched: list[dict[str, Any]] = []
    seen: set[str] = set()

    def push(sec: dict[str, Any]) -> None:
        if sec["section_id"] in seen:
            return
        seen.add(sec["section_id"])
        matched.append(_as_result(sec))

    # 1. Exact section number ("5.4").
    for s in sections:
        if query_norm == s["number"] or query_norm == s["section_id"].lower():
            push(s)

    # 2. Whole parent section ("5" -> 5.1 .. 5.5).
    if not matched and re.fullmatch(r"\d+", query_norm):
        for s in sorted(
            (x for x in sections if x["parent_number"] == query_norm),
            key=_section_sort_key,
        ):
            push(s)

    # 3. Title / parent-title substring.
    if not matched and query_norm:
        for s in sections:
            if query_norm in s["title"].lower() or query_norm in s["parent_title"].lower():
                push(s)

    # 4. Generated knowledge/ file lookup (`knowledge/section-5.4.md`).
    if not matched and KNOWLEDGE_DIR.exists() and query_norm:
        for md_file in sorted(KNOWLEDGE_DIR.rglob("*.md")):
            if md_file.name in ("log.md", "index.md"):
                continue
            if query_norm in md_file.stem.lower() or query_norm in md_file.parent.name.lower():
                file_text = md_file.read_text(encoding="utf-8")
                key = md_file.stem
                if key in seen:
                    continue
                seen.add(key)
                matched.append(
                    {
                        "section_id": md_file.stem.replace("section-", "Section "),
                        "title": md_file.stem,
                        "content": file_text[:_MAX_CONTENT_CHARS],
                        "citation_url": f"file://{md_file.resolve()}",
                        "parent_section": "",
                        "knowledge_url": f"file://{md_file.resolve()}",
                    }
                )

    # 5. Fall back to keyword search so topic words still resolve.
    if not matched and query_norm:
        terms = _build_query_terms(raw)
        scored = [
            (score, s)
            for s in sections
            if (score := _score_section(s, terms, raw)) >= _SCORE_THRESHOLD
        ]
        scored.sort(key=lambda x: (-x[0], _section_sort_key(x[1])))
        for _score, s in scored[:_MAX_RESULTS]:
            push(s)

    if not matched:
        return {
            "status": "NOT_FOUND",
            "message": (
                f"No policy concept matching '{concept_id}' was found in "
                "elevate-apac-m3-policydoc.md."
            ),
        }

    return {
        "status": "SUCCESS",
        "matches": matched[:_MAX_RESULTS],
        "citation_instruction": "Always cite the exact Section ID (e.g. Section X.Y) in your response.",
    }


def search_policy(query: str, caller_id: str = "EMP-1001") -> dict[str, Any]:
    """Search the official Altostrat Singapore Employee Policy Handbook (`elevate-apac-m3-policydoc.md`) by keywords or natural language question.

    Use this tool FIRST for any HR/IT policy question (leave rules, expense limits, gifts,
    work from home equipment allowance, relocation allowance, ITSM ticket lifecycle and
    priority rules, romantic relationships, childcare cap, TOIL, sick leave certificates, etc.).
    Japanese questions are supported and are expanded to the English handbook vocabulary.

    Args:
        query: Search keywords or question (e.g., "home office equipment allowance",
               "relocation allowance cap", "ticket lifecycle New Closed", "TOIL",
               "有給休暇は何日ですか").
        caller_id: Employee ID of the user running the search (default: EMP-1001).

    Returns:
        Top matching policy sections with verbatim text and exact `Section X.Y` citations.
    """
    log_audit_event(
        actor_id=caller_id,
        target_employee_id=caller_id,
        tool_name="search_policy",
        target_system="PolicyKnowledgeBase",
        action_type="READ",
        decision="ALLOW",
        request_summary={"query": query},
    )

    sections = _get_sections()
    terms = _build_query_terms(query or "")

    scored: list[tuple[float, dict[str, Any]]] = []
    if terms:
        for s in sections:
            score = _score_section(s, terms, query or "")
            if score >= _SCORE_THRESHOLD:
                scored.append((score, s))

    # Deterministic ordering: score desc, then document order.
    scored.sort(key=lambda x: (-x[0], _section_sort_key(x[1])))

    top_results = [_as_result(s, score) for score, s in scored[:_MAX_RESULTS]]

    if not top_results:
        return {
            "status": "NO_MATCH",
            "query": query,
            "message": (
                "No matching policy section found in elevate-apac-m3-policydoc.md. "
                "Per Grounding Enforcement (UC-1.1), do NOT guess or extrapolate unstated benefits."
            ),
        }

    return {
        "status": "SUCCESS",
        "query": query,
        "results": top_results,
        "grounding_notice": (
            "MANDATORY: Base your answer strictly on the verbatim 'content' returned above "
            "and cite the specific Section ID (e.g., Section 5.4, Section 25.3). If a benefit "
            "or allowance is not explicitly stated in the text, state that it is not provided in the policy."
        ),
    }
