#!/usr/bin/env python3
"""Regenerate `knowledge/` from `elevate-apac-m3-policydoc.md` (single source of truth).

The official handbook uses bold-text headings (`**SECTION N: TITLE**` and
`**N.M Title**`) rather than ATX markdown headings.  This script reuses the very
same parser that `app/tools/policy_tools.py` uses at runtime, so the generated
files can never drift from what the retrieval tool sees.

Output layout (flat, matches `policy_tools.KNOWLEDGE_FILE_TEMPLATE`)::

    knowledge/index.md
    knowledge/section-1.1.md
    knowledge/section-5.4.md
    ...

Each file starts with YAML front matter carrying the section number, title and
parent-section metadata.

Usage:
    .venv/bin/python scripts/build_knowledge.py [--check]

`--check` parses and reports without writing anything.
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
POLICY_TOOLS_PATH = REPO_ROOT / "app" / "tools" / "policy_tools.py"


def _load_policy_tools() -> Any:
    """Load `policy_tools` directly by path (bypasses `app/tools/__init__.py`)."""
    spec = importlib.util.spec_from_file_location(
        "_build_knowledge_policy_tools", POLICY_TOOLS_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {POLICY_TOOLS_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _yaml_escape(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _front_matter(section: dict[str, Any]) -> str:
    # Built separately: nesting an f-string inside an f-string requires
    # Python 3.12+, and this project supports 3.11.
    source_lines = f"L{section['line_start']}-L{section['line_end']}"
    lines = [
        "---",
        f"section_id: {_yaml_escape(section['section_id'])}",
        f"number: {_yaml_escape(section['number'])}",
        f"title: {_yaml_escape(section['title'])}",
        f"parent_section_id: {_yaml_escape(section['parent_section_id'])}",
        f"parent_number: {_yaml_escape(section['parent_number'])}",
        f"parent_title: {_yaml_escape(section['parent_title'])}",
        f"source: {_yaml_escape('elevate-apac-m3-policydoc.md')}",
        f"source_lines: {_yaml_escape(source_lines)}",
        "---",
    ]
    return "\n".join(lines)


def build(check_only: bool = False) -> int:
    pt = _load_policy_tools()
    sections = pt.parse_policy_document()
    if not sections:
        print("ERROR: no sections parsed from the handbook", file=sys.stderr)
        return 1

    knowledge_dir: Path = pt.KNOWLEDGE_DIR
    print(f"Parsed {len(sections)} sections from {pt.POLICY_DOC_PATH.name}")

    parents: dict[str, str] = {}
    for s in sections:
        if s["parent_number"]:
            parents.setdefault(s["parent_number"], s["parent_title"])

    if check_only:
        for s in sections:
            print(f"  {s['section_id']:<16} {s['title'][:70]}")
        return 0

    if knowledge_dir.exists():
        shutil.rmtree(knowledge_dir)
    knowledge_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    index_lines = [
        "# Altostrat Singapore Employee Policy Handbook — Knowledge Index",
        "",
        "> Generated by `scripts/build_knowledge.py` from `elevate-apac-m3-policydoc.md`.",
        "> Do not edit by hand; re-run the script instead.",
        "",
        f"Total sections: **{len(sections)}**",
        "",
    ]

    last_parent = None
    for section in sections:
        filename = pt.KNOWLEDGE_FILE_TEMPLATE.format(number=section["number"])
        path = knowledge_dir / filename
        body = (
            f"{_front_matter(section)}\n\n"
            f"# Section {section['number']} — {section['title']}\n\n"
            f"**Parent:** {section['parent_section_id']}: {section['parent_title']}\n\n"
            f"{section['content']}\n"
        )
        path.write_text(body, encoding="utf-8")
        written += 1

        if section["parent_number"] != last_parent:
            last_parent = section["parent_number"]
            index_lines.append(
                f"\n## SECTION {section['parent_number']}: {section['parent_title']}\n"
            )
        index_lines.append(
            f"- [`Section {section['number']}` — {section['title']}]({filename})"
        )

    (knowledge_dir / "index.md").write_text(
        "\n".join(index_lines) + "\n", encoding="utf-8"
    )

    print(f"Wrote {written} section files + index.md to {knowledge_dir}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Parse and list sections without writing files.",
    )
    args = parser.parse_args()
    return build(check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
